Fix/history partial loaded error
soramitsu/x-networking pull request #70
Opened 2022-11-15 14:54 UTC by mrZizik

2022-11-15 17:06 UTC, VitalyPeryatin requested changes

2022-11-15 17:06 UTC, VitalyPeryatin commented on AppCommonNetworking/XNetworking/src/commonMain/kotlin/jp/co/soramitsu/xnetworking/txhistory/client/SubQueryClient.kt
> +            hasErrorOnLoading = hasErrorOnLoading
I think we can use more short names without meaning missing: `hasError`, for example
It's not critical, of course. It's up to you :)

2022-11-15 17:06 UTC, VitalyPeryatin commented on AppCommonNetworking/XNetworking/build.gradle.kts
> +version = "0.0.43"
We added new variable `hasErrorOnLoading` in `TxHistoryResult` model. It is binary not compatible changes for Kotlin and require major update for correct library update in application. Otherwise it can crash app in some cases. 
I think we need this version:
`version = "0.1.0"`

2022-11-15 17:06 UTC, VitalyPeryatin commented on AppCommonNetworking/.idea/deploymentTargetDropDown.xml
> +<project version="4">
I think we need to exclude this file from git tracking. This file will be different for each developer

2022-11-15 17:29 UTC, mrZizik commented on AppCommonNetworking/XNetworking/src/commonMain/kotlin/jp/co/soramitsu/xnetworking/txhistory/client/SubQueryClient.kt
> +            try {
Fixed

2022-11-15 17:29 UTC, mrZizik commented on AppCommonNetworking/XNetworking/src/commonMain/kotlin/jp/co/soramitsu/xnetworking/txhistory/client/SubQueryClient.kt
> +            hasErrorOnLoading = hasErrorOnLoading
Fixed

2022-11-15 17:29 UTC, mrZizik commented on AppCommonNetworking/.idea/deploymentTargetDropDown.xml
> +<project version="4">
fixed

2022-11-16 10:14 UTC, arvifox approved these changes

2022-11-16 10:19 UTC, VitalyPeryatin approved these changes

2022-11-16 10:19 UTC, merged